CREATE TABLE tbTurma(
SIGLA_TURMA VARCHAR(2) NOT NULL,
SIGLA_CURSO VARCHAR(2) NOT NULL,
NOME_T VARCHAR2(50) NOT NULL,
QNT_VAGAS INT,
DT_INICIO VARCHAR2(10),
PERIODO VARCHAR2(50),
DT_TERM VARCHAR2(10)
);

CREATE TABLE tbCurso(
SIGLA_CURSO VARCHAR2(2) NOT NULL,
NOME_CURSO VARCHAR2(40) NOT NULL,
CARGA_HORARIA INT NOT NULL,
VALOR NUMBER(10,2) NOT NULL,
PROGRAMA VARCHAR2(50),
DATA_VIGENCIA VARCHAR2(10),
VALOR_HORA_INSTRUTOR NUMBER(8,2)
);

CREATE TABLE tbInstrutor(
CPF VARCHAR2(11) NOT NULL,
NOME_INST VARCHAR(100) NOT NULL,
DT_NASC VARCHAR2(10) NOT NULL,
SEXO VARCHAR(8) NOT NULL,
CIVIL VARCHAR(40),
ENDERECO VARCHAR2(255) NOT NULL,
NUM VARCHAR2(4) NOT NULL,
CEP VARCHAR2(8),
BAIRRO VARCHAR2(255),
TELEFONE VARCHAR2(10),
CELULAR VARCHAR2(11),
CIDADE VARCHAR(50),
UF VARCHAR(2),
RG VARCHAR2(13) NOT NULL,
AREA_ATUACAO VARCHAR2(30),
FORMACAO VARCHAR2(30),
EMAIL VARCHAR2(100) NOT NULL
);

CREATE TABLE tbAluno(
CPF VARCHAR2(11) NOT NULL,
NOME_INST VARCHAR(100) NOT NULL,
DT_NASC DATE NOT NULL,
SEXO VARCHAR(8) NOT NULL,
CIVIL VARCHAR(30),
ESCOLARIDADE VARCHAR(40),
ENDERECO VARCHAR2(255) NOT NULL,
NUM VARCHAR2(4),
CEP VARCHAR2(8),
CIDADE VARCHAR(50),
UF VARCHAR(2),
BAIRRO VARCHAR2(255),
TELEFONE VARCHAR2(10),
CELULAR VARCHAR2(11),
RG VARCHAR2(13) NOT NULL,
EMAIL VARCHAR2(100) NOT NULL
);


ALTER TABLE tbTurma ADD CONSTRAINT PK_SIGLA_TURMA PRIMARY KEY (SIGLA_TURMA);
ALTER TABLE tbCurso ADD CONSTRAINT PK_SIGLA_CURSO PRIMARY KEY (SIGLA_CURSO);
ALTER TABLE tbInstrutor ADD CONSTRAINT PK_INSTRUTORCPF PRIMARY KEY (CPF);
ALTER TABLE tbAluno ADD CONSTRAINT PK_ALUNOCPF PRIMARY KEY (CPF);
ALTER TABLE tbTurma ADD CONSTRAINT FK_SIGLA_CURSO FOREIGN KEY (SIGLA_CURSO) REFERENCES tbCurso(SIGLA_CURSO);
