/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fatec.poo.model.view;

/**
 *
 * @author leona
 */
public class Curso extends javax.swing.JFrame {

    /**
     * Creates new form Curso
     */
    public Curso() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlblSigCur = new javax.swing.JLabel();
        jlblNmCuso = new javax.swing.JLabel();
        jlblCgHor = new javax.swing.JLabel();
        jlblValCur = new javax.swing.JLabel();
        jlblProCur = new javax.swing.JLabel();
        jtxtSigCur = new javax.swing.JTextField();
        jtxtNmCur = new javax.swing.JTextField();
        jtxtCgHor = new javax.swing.JTextField();
        jtxtValCur = new javax.swing.JTextField();
        jtxtProCur = new javax.swing.JTextField();
        jlblCgHor1 = new javax.swing.JLabel();
        jlblValCur1 = new javax.swing.JLabel();
        jtxtValCur1 = new javax.swing.JTextField();
        jfrmtxtCgHor = new javax.swing.JFormattedTextField();
        jbtnCons = new javax.swing.JButton();
        jbtnInc = new javax.swing.JButton();
        jbtnAlt = new javax.swing.JButton();
        jbtnExc = new javax.swing.JButton();
        jbtnSair = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Curso");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jlblSigCur.setText("Sigla Curso");

        jlblNmCuso.setText("Nome Curso");

        jlblCgHor.setText("Carga Horária");

        jlblValCur.setText("Valor Curso");

        jlblProCur.setText("Programa do curso");

        jtxtNmCur.setEnabled(false);

        jtxtCgHor.setEnabled(false);

        jtxtValCur.setEnabled(false);

        jtxtProCur.setEnabled(false);

        jlblCgHor1.setText("Carga Horária");

        jlblValCur1.setText("Valor Curso");

        jtxtValCur1.setEnabled(false);

        try {
            jfrmtxtCgHor.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jfrmtxtCgHor.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jfrmtxtCgHor.setEnabled(false);
        jfrmtxtCgHor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jfrmtxtCgHorActionPerformed(evt);
            }
        });

        jbtnCons.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/consultar.png"))); // NOI18N
        jbtnCons.setText("Consultar");
        jbtnCons.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnConsActionPerformed(evt);
            }
        });

        jbtnInc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/Inserir.png"))); // NOI18N
        jbtnInc.setText("Inserir");
        jbtnInc.setEnabled(false);
        jbtnInc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnIncActionPerformed(evt);
            }
        });

        jbtnAlt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/Alterar.png"))); // NOI18N
        jbtnAlt.setText("Alterar");
        jbtnAlt.setEnabled(false);
        jbtnAlt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnAltActionPerformed(evt);
            }
        });

        jbtnExc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/Excluir.png"))); // NOI18N
        jbtnExc.setText("Excluir");
        jbtnExc.setEnabled(false);
        jbtnExc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnExcActionPerformed(evt);
            }
        });

        jbtnSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/Sair.jpg"))); // NOI18N
        jbtnSair.setText("Sair");
        jbtnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlblSigCur, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jlblNmCuso, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jlblCgHor, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jlblValCur, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jlblProCur, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtxtProCur, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtNmCur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtSigCur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtxtValCur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxtCgHor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlblCgHor1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jlblValCur1, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtxtValCur1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jfrmtxtCgHor, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addComponent(jbtnCons, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtnInc, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtnAlt, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtnExc, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtnSair, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jtxtCgHor, jtxtNmCur, jtxtProCur, jtxtSigCur, jtxtValCur});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jfrmtxtCgHor, jtxtValCur1});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblSigCur)
                    .addComponent(jtxtSigCur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblNmCuso)
                    .addComponent(jtxtNmCur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlblCgHor)
                            .addComponent(jtxtCgHor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlblValCur)
                            .addComponent(jtxtValCur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlblCgHor1)
                            .addComponent(jfrmtxtCgHor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlblValCur1)
                            .addComponent(jtxtValCur1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblProCur)
                    .addComponent(jtxtProCur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnCons)
                    .addComponent(jbtnInc)
                    .addComponent(jbtnAlt)
                    .addComponent(jbtnExc)
                    .addComponent(jbtnSair))
                .addGap(33, 33, 33))
        );

        setSize(new java.awt.Dimension(634, 347));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jfrmtxtCgHorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jfrmtxtCgHorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jfrmtxtCgHorActionPerformed

    private void jbtnConsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnConsActionPerformed
        
    }//GEN-LAST:event_jbtnConsActionPerformed

    private void jbtnIncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnIncActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnIncActionPerformed

    private void jbtnAltActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnAltActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnAltActionPerformed

    private void jbtnExcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnExcActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnExcActionPerformed

    private void jbtnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSairActionPerformed
        this.dispose();
    }//GEN-LAST:event_jbtnSairActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Curso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Curso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Curso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Curso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Curso().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbtnAlt;
    private javax.swing.JButton jbtnCons;
    private javax.swing.JButton jbtnExc;
    private javax.swing.JButton jbtnInc;
    private javax.swing.JButton jbtnSair;
    private javax.swing.JFormattedTextField jfrmtxtCgHor;
    private javax.swing.JLabel jlblCgHor;
    private javax.swing.JLabel jlblCgHor1;
    private javax.swing.JLabel jlblNmCuso;
    private javax.swing.JLabel jlblProCur;
    private javax.swing.JLabel jlblSigCur;
    private javax.swing.JLabel jlblValCur;
    private javax.swing.JLabel jlblValCur1;
    private javax.swing.JTextField jtxtCgHor;
    private javax.swing.JTextField jtxtNmCur;
    private javax.swing.JTextField jtxtProCur;
    private javax.swing.JTextField jtxtSigCur;
    private javax.swing.JTextField jtxtValCur;
    private javax.swing.JTextField jtxtValCur1;
    // End of variables declaration//GEN-END:variables
}
