/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fatec.poo.model.view;

/**
 *
 * @author leona
 */
public class GUIMenu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public GUIMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuCadastrosCurso = new javax.swing.JMenuItem();
        jMenuCadastrosTurma = new javax.swing.JMenuItem();
        jMenuCadastrosInstrutor = new javax.swing.JMenuItem();
        jMenuCadastrosAluno = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuCadastrosSair = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuOperacoesAlocar = new javax.swing.JMenuItem();
        jMenuOperacoesMatricula = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu");

        jMenu1.setText("Cadastros");

        jMenuCadastrosCurso.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, 0));
        jMenuCadastrosCurso.setText("Curso");
        jMenuCadastrosCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCadastrosCursoActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuCadastrosCurso);

        jMenuCadastrosTurma.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, 0));
        jMenuCadastrosTurma.setText("Turma");
        jMenuCadastrosTurma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCadastrosTurmaActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuCadastrosTurma);

        jMenuCadastrosInstrutor.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, 0));
        jMenuCadastrosInstrutor.setText("Instrutor");
        jMenuCadastrosInstrutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCadastrosInstrutorActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuCadastrosInstrutor);

        jMenuCadastrosAluno.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, 0));
        jMenuCadastrosAluno.setText("Aluno");
        jMenuCadastrosAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCadastrosAlunoActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuCadastrosAluno);
        jMenu1.add(jSeparator1);

        jMenuCadastrosSair.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, 0));
        jMenuCadastrosSair.setText("Sair");
        jMenuCadastrosSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCadastrosSairActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuCadastrosSair);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Operações");

        jMenuOperacoesAlocar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, 0));
        jMenuOperacoesAlocar.setText("Alocar Instrutor");
        jMenu2.add(jMenuOperacoesAlocar);

        jMenuOperacoesMatricula.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, 0));
        jMenuOperacoesMatricula.setText("Efetuar Matrícula");
        jMenu2.add(jMenuOperacoesMatricula);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 274, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(418, 347));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuCadastrosCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCadastrosCursoActionPerformed
        new GUICurso().setVisible(true);
    }//GEN-LAST:event_jMenuCadastrosCursoActionPerformed

    private void jMenuCadastrosSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCadastrosSairActionPerformed
       this.dispose();
    }//GEN-LAST:event_jMenuCadastrosSairActionPerformed

    private void jMenuCadastrosTurmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCadastrosTurmaActionPerformed
        new GUITurma().setVisible(true);
    }//GEN-LAST:event_jMenuCadastrosTurmaActionPerformed

    private void jMenuCadastrosAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCadastrosAlunoActionPerformed
        new GUIAluno().setVisible(true);
    }//GEN-LAST:event_jMenuCadastrosAlunoActionPerformed

    private void jMenuCadastrosInstrutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCadastrosInstrutorActionPerformed
        new GUIIntrutor().setVisible(true);
    }//GEN-LAST:event_jMenuCadastrosInstrutorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new GUIMenu().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuCadastrosAluno;
    private javax.swing.JMenuItem jMenuCadastrosCurso;
    private javax.swing.JMenuItem jMenuCadastrosInstrutor;
    private javax.swing.JMenuItem jMenuCadastrosSair;
    private javax.swing.JMenuItem jMenuCadastrosTurma;
    private javax.swing.JMenuItem jMenuOperacoesAlocar;
    private javax.swing.JMenuItem jMenuOperacoesMatricula;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
