/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fatec.poo.model.view;

/**
 *
 * @author leona
 */
public class Instrutor extends javax.swing.JFrame {

    /**
     * Creates new form Instrutor
     */
    public Instrutor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlblEstado = new javax.swing.JLabel();
        jtxtCidade = new javax.swing.JTextField();
        jlblEmail = new javax.swing.JLabel();
        jlblCpf = new javax.swing.JLabel();
        jtxtEmail = new javax.swing.JTextField();
        jtxtNum = new javax.swing.JTextField();
        jlblNum = new javax.swing.JLabel();
        jfrmtxtCep = new javax.swing.JFormattedTextField();
        jlblCep = new javax.swing.JLabel();
        jfrmtxtCpf = new javax.swing.JFormattedTextField();
        jlblTel = new javax.swing.JLabel();
        jlblSexo = new javax.swing.JLabel();
        jcboSexo = new javax.swing.JComboBox<>();
        jlblRg = new javax.swing.JLabel();
        jlblNome = new javax.swing.JLabel();
        jfrmtxtCel = new javax.swing.JFormattedTextField();
        jlblCel = new javax.swing.JLabel();
        jlblEstCivil = new javax.swing.JLabel();
        jfrmtxtTel = new javax.swing.JFormattedTextField();
        jcboEstCivil = new javax.swing.JComboBox<>();
        jfrmtxtRg = new javax.swing.JFormattedTextField();
        jtxtNome = new javax.swing.JTextField();
        jfrmtxtDtNasc = new javax.swing.JFormattedTextField();
        jlblEndereco = new javax.swing.JLabel();
        jlblDtNasc = new javax.swing.JLabel();
        jlblBairro = new javax.swing.JLabel();
        jtxtBairro = new javax.swing.JTextField();
        jlblEndereco2 = new javax.swing.JLabel();
        jtxtEndereco = new javax.swing.JTextField();
        jcboEstado = new javax.swing.JComboBox<>();
        jtxtForm = new javax.swing.JTextField();
        jlblForm = new javax.swing.JLabel();
        jtxtAreaAtua = new javax.swing.JTextField();
        jlblAreaAtua = new javax.swing.JLabel();
        jbtnCons = new javax.swing.JButton();
        jbtnInc = new javax.swing.JButton();
        jbtnAlt = new javax.swing.JButton();
        jbtnExc = new javax.swing.JButton();
        jbtnSair = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Instrutor");

        jlblEstado.setText("Estado");
        jlblEstado.setEnabled(false);

        jtxtCidade.setEnabled(false);

        jlblEmail.setText("Email");
        jlblEmail.setEnabled(false);

        jlblCpf.setText("Cpf");

        jtxtEmail.setEnabled(false);

        jtxtNum.setEnabled(false);

        jlblNum.setText("Nº");
        jlblNum.setEnabled(false);

        try {
            jfrmtxtCep.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("  .   .   -  ")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jfrmtxtCep.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jfrmtxtCep.setEnabled(false);
        jfrmtxtCep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jfrmtxtCepActionPerformed(evt);
            }
        });

        jlblCep.setText("Cep");
        jlblCep.setEnabled(false);

        try {
            jfrmtxtCpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jfrmtxtCpf.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jfrmtxtCpf.setText("");
        jfrmtxtCpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jfrmtxtCpfActionPerformed(evt);
            }
        });

        jlblTel.setText("Tel Res.");
        jlblTel.setEnabled(false);

        jlblSexo.setText("Sexo");
        jlblSexo.setEnabled(false);

        jcboSexo.setEnabled(false);
        jcboSexo.setRequestFocusEnabled(false);

        jlblRg.setText("RG");
        jlblRg.setEnabled(false);

        jlblNome.setText("Nome");
        jlblNome.setEnabled(false);

        try {
            jfrmtxtCel.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jfrmtxtCel.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jfrmtxtCel.setEnabled(false);
        jfrmtxtCel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jfrmtxtCelActionPerformed(evt);
            }
        });

        jlblCel.setText("Celular");
        jlblCel.setEnabled(false);

        jlblEstCivil.setText("Estado Civíl");
        jlblEstCivil.setEnabled(false);

        try {
            jfrmtxtTel.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jfrmtxtTel.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jfrmtxtTel.setEnabled(false);
        jfrmtxtTel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jfrmtxtTelActionPerformed(evt);
            }
        });

        jcboEstCivil.setEnabled(false);
        jcboEstCivil.setRequestFocusEnabled(false);

        try {
            jfrmtxtRg.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jfrmtxtRg.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jfrmtxtRg.setEnabled(false);
        jfrmtxtRg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jfrmtxtRgActionPerformed(evt);
            }
        });

        jtxtNome.setEnabled(false);

        try {
            jfrmtxtDtNasc.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jfrmtxtDtNasc.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jfrmtxtDtNasc.setEnabled(false);
        jfrmtxtDtNasc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jfrmtxtDtNascActionPerformed(evt);
            }
        });

        jlblEndereco.setText("Endereço");
        jlblEndereco.setEnabled(false);

        jlblDtNasc.setText("Data de Nascto");
        jlblDtNasc.setEnabled(false);

        jlblBairro.setText("Bairro");
        jlblBairro.setEnabled(false);

        jtxtBairro.setEnabled(false);

        jlblEndereco2.setText("Cidade");
        jlblEndereco2.setEnabled(false);

        jtxtEndereco.setEnabled(false);

        jcboEstado.setEnabled(false);
        jcboEstado.setRequestFocusEnabled(false);

        jtxtForm.setEnabled(false);

        jlblForm.setText("Formação");
        jlblForm.setEnabled(false);

        jtxtAreaAtua.setEnabled(false);

        jlblAreaAtua.setText("Area de Atuação");
        jlblAreaAtua.setEnabled(false);

        jbtnCons.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/consultar.png"))); // NOI18N
        jbtnCons.setText("Consultar");
        jbtnCons.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnConsActionPerformed(evt);
            }
        });

        jbtnInc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/Inserir.png"))); // NOI18N
        jbtnInc.setText("Inserir");
        jbtnInc.setEnabled(false);
        jbtnInc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnIncActionPerformed(evt);
            }
        });

        jbtnAlt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/Alterar.png"))); // NOI18N
        jbtnAlt.setText("Alterar");
        jbtnAlt.setEnabled(false);
        jbtnAlt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnAltActionPerformed(evt);
            }
        });

        jbtnExc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/Excluir.png"))); // NOI18N
        jbtnExc.setText("Excluir");
        jbtnExc.setEnabled(false);
        jbtnExc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnExcActionPerformed(evt);
            }
        });

        jbtnSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/Sair.jpg"))); // NOI18N
        jbtnSair.setText("Sair");
        jbtnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlblEndereco, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jlblBairro, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jlblEndereco2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jlblSexo, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jlblRg, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jlblNome, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jlblForm, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jlblEmail, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jlblCpf, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtxtBairro)
                                    .addComponent(jtxtEndereco)
                                    .addComponent(jtxtNome)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jfrmtxtRg, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jtxtCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jlblEstado)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jcboEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jtxtEmail))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jlblDtNasc, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jlblNum, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jlblCep, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jlblTel, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jlblCel, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jlblEstCivil, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jfrmtxtDtNasc, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtxtNum, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jfrmtxtCep, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jfrmtxtCel, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jfrmtxtTel, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jcboEstCivil, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap())
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jtxtForm, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jlblAreaAtua)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jtxtAreaAtua))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jfrmtxtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jcboSexo, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addGap(12, 12, 12))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jbtnCons, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtnInc, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtnAlt, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtnExc, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtnSair, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblCpf)
                    .addComponent(jfrmtxtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblNome)
                    .addComponent(jtxtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlblDtNasc)
                    .addComponent(jfrmtxtDtNasc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlblSexo, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jcboSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jlblEstCivil)
                        .addComponent(jcboEstCivil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblEndereco)
                    .addComponent(jtxtEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlblNum)
                    .addComponent(jtxtNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblBairro)
                    .addComponent(jtxtBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlblCep)
                    .addComponent(jfrmtxtCep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlblEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jlblTel)
                        .addComponent(jfrmtxtTel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jlblEndereco2)
                        .addComponent(jtxtCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jcboEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblRg)
                    .addComponent(jfrmtxtRg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlblCel)
                    .addComponent(jfrmtxtCel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblForm)
                    .addComponent(jtxtForm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlblAreaAtua)
                    .addComponent(jtxtAreaAtua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblEmail)
                    .addComponent(jtxtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnCons)
                    .addComponent(jbtnInc)
                    .addComponent(jbtnAlt)
                    .addComponent(jbtnExc)
                    .addComponent(jbtnSair))
                .addGap(42, 42, 42))
        );

        setSize(new java.awt.Dimension(766, 464));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jfrmtxtCepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jfrmtxtCepActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jfrmtxtCepActionPerformed

    private void jfrmtxtCpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jfrmtxtCpfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jfrmtxtCpfActionPerformed

    private void jfrmtxtCelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jfrmtxtCelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jfrmtxtCelActionPerformed

    private void jfrmtxtTelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jfrmtxtTelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jfrmtxtTelActionPerformed

    private void jfrmtxtRgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jfrmtxtRgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jfrmtxtRgActionPerformed

    private void jfrmtxtDtNascActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jfrmtxtDtNascActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jfrmtxtDtNascActionPerformed

    private void jbtnConsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnConsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnConsActionPerformed

    private void jbtnIncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnIncActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnIncActionPerformed

    private void jbtnAltActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnAltActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnAltActionPerformed

    private void jbtnExcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnExcActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnExcActionPerformed

    private void jbtnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSairActionPerformed
        this.dispose();
    }//GEN-LAST:event_jbtnSairActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Instrutor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Instrutor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Instrutor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Instrutor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Instrutor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbtnAlt;
    private javax.swing.JButton jbtnCons;
    private javax.swing.JButton jbtnExc;
    private javax.swing.JButton jbtnInc;
    private javax.swing.JButton jbtnSair;
    private javax.swing.JComboBox<String> jcboEstCivil;
    private javax.swing.JComboBox<String> jcboEstado;
    private javax.swing.JComboBox<String> jcboSexo;
    private javax.swing.JFormattedTextField jfrmtxtCel;
    private javax.swing.JFormattedTextField jfrmtxtCep;
    private javax.swing.JFormattedTextField jfrmtxtCpf;
    private javax.swing.JFormattedTextField jfrmtxtDtNasc;
    private javax.swing.JFormattedTextField jfrmtxtRg;
    private javax.swing.JFormattedTextField jfrmtxtTel;
    private javax.swing.JLabel jlblAreaAtua;
    private javax.swing.JLabel jlblBairro;
    private javax.swing.JLabel jlblCel;
    private javax.swing.JLabel jlblCep;
    private javax.swing.JLabel jlblCpf;
    private javax.swing.JLabel jlblDtNasc;
    private javax.swing.JLabel jlblEmail;
    private javax.swing.JLabel jlblEndereco;
    private javax.swing.JLabel jlblEndereco2;
    private javax.swing.JLabel jlblEstCivil;
    private javax.swing.JLabel jlblEstado;
    private javax.swing.JLabel jlblForm;
    private javax.swing.JLabel jlblNome;
    private javax.swing.JLabel jlblNum;
    private javax.swing.JLabel jlblRg;
    private javax.swing.JLabel jlblSexo;
    private javax.swing.JLabel jlblTel;
    private javax.swing.JTextField jtxtAreaAtua;
    private javax.swing.JTextField jtxtBairro;
    private javax.swing.JTextField jtxtCidade;
    private javax.swing.JTextField jtxtEmail;
    private javax.swing.JTextField jtxtEndereco;
    private javax.swing.JTextField jtxtForm;
    private javax.swing.JTextField jtxtNome;
    private javax.swing.JTextField jtxtNum;
    // End of variables declaration//GEN-END:variables
}
