/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fatec.poo.model.view;

/**
 *
 * @author leona
 */
public class Turma extends javax.swing.JFrame {

    /**
     * Creates new form Turma
     */
    public Turma() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtxtNome = new javax.swing.JTextField();
        jtxtQtdVagas = new javax.swing.JTextField();
        jlblCurso = new javax.swing.JLabel();
        jlblSigTurma = new javax.swing.JLabel();
        jlblPeriodo = new javax.swing.JLabel();
        jlblNome = new javax.swing.JLabel();
        jlblQtdVagas = new javax.swing.JLabel();
        jtxtSigTurma = new javax.swing.JTextField();
        jlblDtIni = new javax.swing.JLabel();
        jfrmtxtDtIni = new javax.swing.JFormattedTextField();
        jlblDtfim = new javax.swing.JLabel();
        jfrmtxtDtfim = new javax.swing.JFormattedTextField();
        jcboPeriodo = new javax.swing.JComboBox<>();
        jcboCurso = new javax.swing.JComboBox<>();
        jbtnCons = new javax.swing.JButton();
        jbtnInc = new javax.swing.JButton();
        jbtnAlt = new javax.swing.JButton();
        jbtnExc = new javax.swing.JButton();
        jbtnSair = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Turma");

        jtxtNome.setEnabled(false);

        jtxtQtdVagas.setEnabled(false);

        jlblCurso.setText("Curso");

        jlblSigTurma.setText("Sigla Turma");

        jlblPeriodo.setText("Periodo");

        jlblNome.setText("Nome");

        jlblQtdVagas.setText("Qtd Vagas");

        jtxtSigTurma.setEnabled(false);

        jlblDtIni.setText("Data de Início");

        try {
            jfrmtxtDtIni.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jfrmtxtDtIni.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jfrmtxtDtIni.setEnabled(false);
        jfrmtxtDtIni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jfrmtxtDtIniActionPerformed(evt);
            }
        });

        jlblDtfim.setText("Data de Término");

        try {
            jfrmtxtDtfim.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jfrmtxtDtfim.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jfrmtxtDtfim.setEnabled(false);
        jfrmtxtDtfim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jfrmtxtDtfimActionPerformed(evt);
            }
        });

        jcboPeriodo.setEnabled(false);

        jcboCurso.setEditable(true);

        jbtnCons.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/consultar.png"))); // NOI18N
        jbtnCons.setText("Consultar");
        jbtnCons.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnConsActionPerformed(evt);
            }
        });

        jbtnInc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/Inserir.png"))); // NOI18N
        jbtnInc.setText("Inserir");
        jbtnInc.setEnabled(false);
        jbtnInc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnIncActionPerformed(evt);
            }
        });

        jbtnAlt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/Alterar.png"))); // NOI18N
        jbtnAlt.setText("Alterar");
        jbtnAlt.setEnabled(false);
        jbtnAlt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnAltActionPerformed(evt);
            }
        });

        jbtnExc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/Excluir.png"))); // NOI18N
        jbtnExc.setText("Excluir");
        jbtnExc.setEnabled(false);
        jbtnExc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnExcActionPerformed(evt);
            }
        });

        jbtnSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/Sair.jpg"))); // NOI18N
        jbtnSair.setText("Sair");
        jbtnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlblDtIni, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jlblQtdVagas, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jlblNome, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jlblSigTurma, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jlblCurso, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jtxtQtdVagas, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(119, 119, 119)
                                .addComponent(jcboPeriodo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jlblPeriodo)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jfrmtxtDtIni, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jlblDtfim)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jfrmtxtDtfim, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jtxtNome)
                            .addComponent(jcboCurso, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jtxtSigTurma, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jbtnCons, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtnInc, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtnAlt, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtnExc, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtnSair, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblCurso)
                    .addComponent(jcboCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblSigTurma)
                    .addComponent(jtxtSigTurma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblNome)
                    .addComponent(jtxtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblQtdVagas)
                    .addComponent(jtxtQtdVagas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlblPeriodo)
                    .addComponent(jcboPeriodo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblDtIni)
                    .addComponent(jfrmtxtDtIni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlblDtfim)
                    .addComponent(jfrmtxtDtfim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnCons)
                    .addComponent(jbtnInc)
                    .addComponent(jbtnAlt)
                    .addComponent(jbtnExc)
                    .addComponent(jbtnSair))
                .addGap(36, 36, 36))
        );

        setSize(new java.awt.Dimension(625, 336));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jfrmtxtDtIniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jfrmtxtDtIniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jfrmtxtDtIniActionPerformed

    private void jfrmtxtDtfimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jfrmtxtDtfimActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jfrmtxtDtfimActionPerformed

    private void jbtnConsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnConsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnConsActionPerformed

    private void jbtnIncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnIncActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnIncActionPerformed

    private void jbtnAltActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnAltActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnAltActionPerformed

    private void jbtnExcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnExcActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnExcActionPerformed

    private void jbtnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSairActionPerformed
        this.dispose();
    }//GEN-LAST:event_jbtnSairActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Turma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Turma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Turma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Turma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Turma().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbtnAlt;
    private javax.swing.JButton jbtnCons;
    private javax.swing.JButton jbtnExc;
    private javax.swing.JButton jbtnInc;
    private javax.swing.JButton jbtnSair;
    private javax.swing.JComboBox<String> jcboCurso;
    private javax.swing.JComboBox<String> jcboPeriodo;
    private javax.swing.JFormattedTextField jfrmtxtDtIni;
    private javax.swing.JFormattedTextField jfrmtxtDtfim;
    private javax.swing.JLabel jlblCurso;
    private javax.swing.JLabel jlblDtIni;
    private javax.swing.JLabel jlblDtfim;
    private javax.swing.JLabel jlblNome;
    private javax.swing.JLabel jlblPeriodo;
    private javax.swing.JLabel jlblQtdVagas;
    private javax.swing.JLabel jlblSigTurma;
    private javax.swing.JTextField jtxtNome;
    private javax.swing.JTextField jtxtQtdVagas;
    private javax.swing.JTextField jtxtSigTurma;
    // End of variables declaration//GEN-END:variables
}
